server:
  port: 8080
spring:
  application:
    name: course
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:15432/devdojo?ApplicationName=course
    username: postgres
    password: postgres
